"""TAXONOMY.md, generated from taxonomy.py and schema.py so the codes and the docs never drift.

python -m pipeline taxonomy   rewrites TAXONOMY.md; a test fails if the committed file is stale.
"""
from pathlib import Path

from . import taxonomy as T
from .schema import V

KIND_MEANING = {
    "money_received": "Money received from a person",
    "money_sent": "Money sent to a person",
    "agent_cash_in": "Cash deposited through an agent",
    "agent_cash_out": "Cash withdrawn through an agent (agent side)",
    "agent_withdrawal": "Cash withdrawn through an agent (customer side)",
    "loan_offer": "Offer to borrow, buy on credit or pay later",
    "agent_info": "Notice to agents or merchants (commissions, activations, tools)",
    "service_subscription": "Subscription to a content or value-added service",
    "account_notice": "Account, balance, maintenance or support notice",
    "security_tip": "Anti-fraud advice or self-service recovery steps",
    "bank_alert": "Bank debit, credit, card or banking-app message",
    "government_notice": "Passport, ID or other public-service notice",
    "merchant_debit": "Payment taken by a merchant or service",
    "bill_payment": "Bill or utility payment confirmation",
    "loan_advance": "Loan or advance received",
    "loan_repayment": "Loan or advance repaid",
    "airtime_topup": "Airtime top-up received",
    "otp_code": "One-time or verification code (the code itself is masked)",
    "promo": "Bundle, bonus, contest or marketing offer",
    "other": "Other",
}

OPERATOR_MEANING = {
    "mtn": "MTN Cameroon (incl. MoMo and services sent under MTN sender names)",
    "orange": "Orange Cameroun (incl. Orange Money)",
    "camtel": "Camtel",
    "nexttel": "Nexttel",
    "bank": "A bank",
    "government": "A public body",
    "online_service": "An online service (Google, WhatsApp, Payoneer...)",
    "partner_brand": "A brand sending through an operator (phone makers, utilities, content)",
    "unknown": "Not known",
}


def _codes(values):
    return ", ".join(f"`{v}`" for v in values)


def taxonomy_md() -> str:
    out = ["# Taxonomy", "", "Codes used in every file. Generated by `python -m pipeline taxonomy` from "
           "`pipeline/taxonomy.py` and `pipeline/schema.py`; do not edit by hand.", "",
           "## Scam types (`scam_types`)", "", "| Code | Meaning |", "|---|---|"]
    out += [f"| `{k}` | {v} |" for k, v in T.SCAM_TYPES.items()]
    simple = [
        ("Channels", "channel / channels", T.CHANNELS),
        ("Requested actions", "caller_asked / requested_actions", T.REQUESTED_ACTIONS),
        ("Outcomes", "outcome", T.OUTCOMES),
        ("Payment rails", "payment_rails", T.PAYMENT_RAILS),
        ("Sender types", "sender_type", T.SENDER_TYPES),
        ("Regions", "region", T.REGIONS),
        ("What people did after", "actions_after", V["actions_after"]),
        ("When it happened", "when", list(dict.fromkeys(T.FORM_WHEN.values()))),
        ("How a call ended", "call_end", list(dict.fromkeys(T.FORM_CALL_END.values()))),
        ("Who the caller claimed to be", "caller_claimed", list(dict.fromkeys(T.FORM_CALLER_CLAIM.values()))),
        ("Languages", "message_language / call_language", T.LANGUAGES),
        ("Where the message text came from", "text_origin", V["text_origin"]),
    ]
    for title, field, values in simple:
        out += ["", f"## {title} (`{field}`)", "", _codes(values)]
    out += ["", "`text_origin`: `pasted` by the person, read from a `screenshot`, transcribed and checked by hand "
            "(`reviewed`), or the person's own account of a call or chat (`retold`).",
            "", "## Genuine messages: operator (`operator`)", "", "| Code | Meaning |", "|---|---|"]
    out += [f"| `{k}` | {OPERATOR_MEANING[k]} |" for k in V["operator"]]
    out += ["", "## Genuine messages: line type (`line_type`)", "", _codes(V["line_type"]),
            "", "## Genuine messages: kind (`message_kind`)", "", "| Code | Meaning |", "|---|---|"]
    out += [f"| `{k}` | {KIND_MEANING[k]} |" for k in V["message_kind"]]
    return "\n".join(out) + "\n"


def write_taxonomy(root: Path) -> Path:
    path = root / "TAXONOMY.md"
    path.write_text(taxonomy_md(), encoding="utf-8")
    return path
